spring:
 application:
  name: 'wallets-domain-service'

app:
 base:
  uri: '/wallets-domain-service/api/v1'

web-client:
 services:
  wallet-service:
   base-uri: 'http://localhost:8085'
   api-prefix: '/api/v1/wallets-service'
   create-wallet-transaction-api: '/wallets/wallet/transaction'
  beneficiary-service:
   base-uri: 'http://localhost:8086'
   api-prefix: '/api/v1/beneficiaries-service'
   get-beneficiary-api: '/beneficiaries/beneficiary/{beneficiaryId}'
  transfer-service:
   base-uri: 'http://localhost:8087'
   api-prefix: '/api/v1/transfers-service'
   do-transfer-api: '/transfers/transfer'
 timeout: 5000

server:
  port: 8088