spring:
  application:
    name: 'transfers-service'

app:
 base:
  uri: '/transfers-service/api/v1'

web-client:
 services:
  transfer-service:
   base-uri: 'http://mockoon.tools.getontop.com:3000'
   api-prefix: '/api/v1'
   do-transfer-api: '/payments'
 timeout: 5000
server:
 port: 8087

transfer:
 source-account:
  ontop:
   source-information:
    name: 'ONTOP INC'
   account:
    account-number: '0245253419'
    currency: 'USD'
    routing-number: '028444018'
